project_id = "uareyloxlpvaxmzygpgo"

[functions.update-prices-cron]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.fetch-underlying-prices]
verify_jwt = false

[functions.fetch-etf-allocation]
verify_jwt = false

[functions.check-alerts]
verify_jwt = false

[functions.update-underlying-prices-cron]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.telegram-link]
verify_jwt = false

[functions.generate-reset-link]
verify_jwt = false

[functions.daily-briefing]
verify_jwt = false

[functions.update-option-prices-cron]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.auto-snapshot]
verify_jwt = false

[functions.massive-proxy]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.fetch-ticker-fundamentals]
verify_jwt = false

[functions.update-erp-cron]
verify_jwt = false

[functions.update-beta-cron]
verify_jwt = false