// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-portfolios.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_portfolios_default = defineTool({
  name: "list_portfolios",
  title: "Elenca portafogli",
  description: "Restituisce l'elenco dei portafogli dell'utente autenticato, con valore totale, cash e data dell'ultimo snapshot.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("portfolios").select(
      "id, name, total_value, cash_value, gp_total_value, snapshot_date, last_updated"
    ).order("name", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { portfolios: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-portfolio-positions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_portfolio_positions_default = defineTool2({
  name: "get_portfolio_positions",
  title: "Posizioni del portafoglio",
  description: "Restituisce le posizioni (azioni, ETF, obbligazioni, derivati) di uno specifico portafoglio dell'utente.",
  inputSchema: {
    portfolio_id: z.string().uuid().describe("UUID del portafoglio da leggere (recuperabile via list_portfolios)."),
    asset_type: z.string().optional().describe(
      "Filtro opzionale sul tipo di asset (es. STOCK, ETF, BOND, OPTION)."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ portfolio_id, asset_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("positions").select(
      "id, asset_type, description, isin, quantity, avg_cost, current_price, market_value, profit_loss, profit_loss_pct, currency, expiry_date, option_type"
    ).eq("portfolio_id", portfolio_id);
    if (asset_type) query = query.eq("asset_type", asset_type);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { positions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-derivative-strategies.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_derivative_strategies_default = defineTool3({
  name: "list_derivative_strategies",
  title: "Strategie derivati",
  description: "Elenca le configurazioni di strategie derivati (Covered Call, Put, Spread, ecc.) mappate per un portafoglio.",
  inputSchema: {
    portfolio_id: z2.string().uuid().describe("UUID del portafoglio.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ portfolio_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("strategy_configurations").select("*").eq("portfolio_id", portfolio_id);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { strategies: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uareyloxlpvaxmzygpgo";
var mcp_default = defineMcp({
  name: "option-tech-mcp",
  title: "Option Tech MCP",
  version: "0.1.0",
  instructions: "Strumenti in sola lettura per accedere ai portafogli Option Tech dell'utente autenticato: elenco portafogli, posizioni per portafoglio e configurazioni di strategie derivati.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_portfolios_default,
    get_portfolio_positions_default,
    list_derivative_strategies_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
